/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rp199.template

import com.rp199.template.service.SampleService
import org.slf4j.LoggerFactory

fun main(args: Array<String>) {
    logger.info("Application started - args: {}", args)
    SampleService().doStuff(args.firstOrNull() ?: "empty args").let {
        logger.info("Result: {}", it)
    }
}

private val logger = LoggerFactory.getLogger("AppKt")